version: '2.1'

networks:
  app-net:

services:
  motus_f:
    build:
      context: ./motus_ms
      dockerfile: ./DockerFile
    image: motus_f
    container_name: motus_f
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app-net
    

  score_f:
    build:
      context: ./score_ms
      dockerfile: ./DockerFile
    image: score_f
    container_name: score_f
    ports:
      - "4000:4000"
    networks:
      - app-net

  
  auth_f:
    build:
      context: ./auth_ms
      dockerfile: ./DockerFile
    image: auth_f
    container_name: auth_f
    ports:
      - "5000:5000"
    networks:
      - app-net